name       : pari
version    : 2.15.4
release    : 1
source     :
    - https://pari.math.u-bordeaux.fr/pub/pari/unix/pari-2.15.4.tar.gz : c3545bfee0c6dfb40b77fb4bbabaf999d82e60069b9f6d28bcb6cf004c8c5c0f
homepage   : https://pari.math.u-bordeaux.fr/
license    : GPL-3.0-or-later
component  : office.scientific
summary    : Computer algebra system designed for fast computations in number theory
description: |
    PARI/GP is a cross platform and open-source computer algebra system designed for fast computations in number theory: factorizations, algebraic number theory, elliptic curves, modular forms, L functions... It also contains a wealth of functions to compute with mathematical entities such as matrices, polynomials, power series, algebraic numbers, etc., and a lot of transcendental functions as well as numerical sumation and integration routines.
builddeps  :
    - texlive
setup      : |
    sed -e 's|DLLDFLAGS  = \$DLLDFLAGS|DLLDFLAGS  = $DLLDFLAGS $LDFLAGS|' -i config/Makefile.SH # Honor system LDFLAGS
    ./Configure \
        --prefix=/usr \
        --with-readline \
        --mt=pthread \
        --with-gmp
build      : |
    %make all
    %make -C Olinux-x86_64 gp-sta
install    : |
    %make_install
    %make -C Olinux-x86_64 install-bin-sta
