name       : gf2x
version    : 1.3.0
release    : 1
source     :
    - https://gitlab.inria.fr/gf2x/gf2x/-/archive/gf2x-1.3.0/gf2x-gf2x-1.3.0.tar.gz : 11bcf98b620c60c2ee3b4460b02b7be741f14cfdc26b542f22c92950926575e0
homepage   : https://gitlab.inria.fr/gf2x/gf2x
license    : GPL-3.0-or-later
component  : office.scientific
summary    : A library for multiplying polynomials over the binary field
description: |
    A library for multiplying polynomials over the binary field
setup      : |
    %reconfigure \
        --enable-sse2 \
        --disable-pclmul \
        CFLAGS="$CFLAGS -msse2"
build      : |
    %make
install    : |
    %make_install
