name       : openblas
version    : 0.3.24
release    : 26
source     :
    - https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.24/OpenBLAS-0.3.24.tar.gz : ceadc5065da97bd92404cac7254da66cc6eb192679cf1002098688978d4d5132
homepage   : https://www.openblas.net/
license    : BSD-3-Clause
component  : programming.library
optimize   :
    - speed
    - lto
avx2       : yes
summary    : OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
description: |
    OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
patterns   :
    - /usr/lib64/libopenblas_core2p*.so
builddeps  :
    - pkgconfig(lapack)
setup      : |
    %apply_patches
environment: |
    if [[ ! -z "${AVX2BUILD}" ]]; then
        export _target="HASWELL"
    else
        export _target="CORE2"
    fi
setup      : |
    FC=gfortran %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_TESTING=OFF \
        -DCORE=${_target} \
        -DDYNAMIC_ARCH=ON \
        -DNO_AFFINITY=ON \
        -DNO_WARMUP=1 \
        -DNUM_THREADS=128 \
        -DUSE_OPENMP=1
build      : |
    %ninja_build
install    : |
    %ninja_install
