name       : r2modman
version    : 3.2.6
release    : 4
source     :
    - https://github.com/ebkr/r2modmanPlus/archive/refs/tags/v3.2.6.tar.gz : 2f6eb986e41c59da0128bb67ac4485573558a1e9442b412304334ca8987ed562
homepage   : https://github.com/ebkr/r2modmanPlus
license    : MIT
component  : games
networking : true
summary    : A simple and easy to use mod manager for games using Thunderstore
description: |
    r2modman is a mod manager with support for Risk of Rain 2, Dyson Sphere Program, Valheim, GTFO, and many other games. It features a clean user interface designed to make modding as simple as possible.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - yarn
setup      : |
    sed -i "s/'AppImage', 'tar.gz', 'deb', 'rpm', 'pacman'/'dir'/g" quasar.config.ts
    yarn install
build      : |
    yarn build-linux
install    : |
    export r2mmdir=/usr/share/r2modman

    # Install and link binary
    install -dm00755 $installdir/$r2mmdir
    cp -R %workdir%/dist/electron/Packaged/linux-unpacked/* $installdir/$r2mmdir/.
    install -dm00755 $installdir/usr/bin
    ln -s $r2mmdir/r2modman $installdir/usr/bin/r2modman

    # Install desktop file
    install -Dm00644 $pkgfiles/io.github.ebkr.r2modman.desktop -t $installdir/usr/share/applications

    # Install icons
    for s in 16x16 24x24 32x32 48x48 64x64 96x96 128x128 192x192 256x256; do
        install -Dm0644 src/assets/icon/${s}.png $installdir/usr/share/icons/hicolor/${s}/apps/r2modman.png
    done

    # Install appstream metadata
    install -Dm00644 $pkgfiles/io.github.ebkr.r2modman.metainfo.xml -t $installdir/usr/share/metainfo
